"""Initial schema

Revision ID: 6d1e0ef540e5
Revises: e14dcf734a5d
Create Date: 2026-05-14 10:03:38.770852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d1e0ef540e5'
down_revision = e14dcf734a5d
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_top_tracks_spotify_id', table_name='user_top_tracks')
    op.drop_index('idx_top_tracks_user_time', table_name='user_top_tracks')
    op.drop_table('user_top_tracks')
    op.drop_index('idx_listening_spotify_id', table_name='listening_history')
    op.drop_index('idx_listening_user_played', table_name='listening_history')
    op.drop_table('listening_history')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_spotify_id', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_spotify_id', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_user_profiles_user_id', table_name='user_profiles')
    op.drop_index('ix_user_profiles_user_id', table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index('idx_notifications_user', table_name='notifications')
    op.drop_index('idx_notifications_user_unread', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_top_artists_spotify_id', table_name='user_top_artists')
    op.drop_index('idx_top_artists_user_time', table_name='user_top_artists')
    op.drop_table('user_top_artists')
    op.drop_index('idx_friendships_receiver', table_name='friendships')
    op.drop_index('idx_friendships_requester', table_name='friendships')
    op.drop_index('idx_friendships_status', table_name='friendships')
    op.drop_table('friendships')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('requester_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('receiver_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name='friendships_receiver_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name='friendships_requester_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='friendships_pkey')
    )
    op.create_index('idx_friendships_status', 'friendships', ['status'], unique=False)
    op.create_index('idx_friendships_requester', 'friendships', ['requester_id'], unique=False)
    op.create_index('idx_friendships_receiver', 'friendships', ['receiver_id'], unique=False)
    op.create_table('user_top_artists',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('spotify_artist_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('artist_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('genres', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('popularity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_range', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_top_artists_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_top_artists_pkey')
    )
    op.create_index('idx_top_artists_user_time', 'user_top_artists', ['user_id', 'time_range'], unique=False)
    op.create_index('idx_top_artists_spotify_id', 'user_top_artists', ['spotify_artist_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('from_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], name='notifications_from_user_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='notifications_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='notifications_pkey')
    )
    op.create_index('idx_notifications_user_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('idx_notifications_user', 'notifications', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('favorite_genres', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('favorite_artists', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('total_hours_listened', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('listening_streak', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_public', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_profiles_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_profiles_pkey')
    )
    op.create_index('ix_user_profiles_user_id', 'user_profiles', ['user_id'], unique=False)
    op.create_index('idx_user_profiles_user_id', 'user_profiles', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('spotify_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('profile_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('spotify_access_token', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('spotify_refresh_token', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('spotify_token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_spotify_sync', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_users_spotify_id', 'users', ['spotify_id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_spotify_id', 'users', ['spotify_id'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_table('listening_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('spotify_track_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('track_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('artist_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('album_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('played_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='listening_history_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='listening_history_pkey')
    )
    op.create_index('idx_listening_user_played', 'listening_history', ['user_id', 'played_at'], unique=False)
    op.create_index('idx_listening_spotify_id', 'listening_history', ['spotify_track_id'], unique=False)
    op.create_table('user_top_tracks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('spotify_track_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('track_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('artist_name', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('album_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_range', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_top_tracks_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_top_tracks_pkey')
    )
    op.create_index('idx_top_tracks_user_time', 'user_top_tracks', ['user_id', 'time_range'], unique=False)
    op.create_index('idx_top_tracks_spotify_id', 'user_top_tracks', ['spotify_track_id'], unique=False)
    # ### end Alembic commands ###